services:
  web-app:
    build: ./web-app
    ports:
      - "8080:8080"
    container_name: web-app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  ml_client:
    build: ./machine-learning-client 
    container_name: ml_client
    environment:
      - MONGO_URI=mongodb://mongo:27017/ 
    depends_on:
      - mongo

volumes:
  mongo-data:
